### ISSUE TITLE
The IME Candidate Window position is not correct

### ISSUE THREAD

**Issue by angshuman-agarwal** [angshuman-agarwal/CEFSHAPRP_WPF#1]
Run the project and change the IME to Japanese.
Start typing
The Candidate Window appears on bottom right of the OS (near system tray)

**Comment by angshuman-agarwal** [comment]
Fixed it - https://github.com/angshuman-agarwal/CEFSHAPRP_WPF/commit/03922c0810ff19822cf17d0b4b69cb9396345086

@alfein

**Comment by alfein** [comment]
Thank you
